# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 611)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Upload_2 = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Upload_2.sizePolicy().hasHeightForWidth())
        self.Upload_2.setSizePolicy(sizePolicy)
        self.Upload_2.setMinimumSize(QtCore.QSize(0, 30))
        self.Upload_2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.Upload_2.setObjectName("Upload_2")
        self.horizontalLayout_6.addWidget(self.Upload_2)
        self.inputComponents1_2 = QtWidgets.QToolButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputComponents1_2.sizePolicy().hasHeightForWidth())
        self.inputComponents1_2.setSizePolicy(sizePolicy)
        self.inputComponents1_2.setMinimumSize(QtCore.QSize(0, 30))
        self.inputComponents1_2.setStyleSheet("selection-background-color: rgb(0, 73, 220);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.inputComponents1_2.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.inputComponents1_2.setObjectName("inputComponents1_2")
        self.horizontalLayout_6.addWidget(self.inputComponents1_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputImage1_2 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputImage1_2.sizePolicy().hasHeightForWidth())
        self.inputImage1_2.setSizePolicy(sizePolicy)
        self.inputImage1_2.setMinimumSize(QtCore.QSize(300, 200))
        self.inputImage1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputImage1_2.setFrameShape(QtWidgets.QFrame.Box)
        self.inputImage1_2.setText("")
        self.inputImage1_2.setObjectName("inputImage1_2")
        self.horizontalLayout_2.addWidget(self.inputImage1_2)
        self.inputImage1Component_2 = PlotWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputImage1Component_2.sizePolicy().hasHeightForWidth())
        self.inputImage1Component_2.setSizePolicy(sizePolicy)
        self.inputImage1Component_2.setMinimumSize(QtCore.QSize(300, 200))
        self.inputImage1Component_2.setObjectName("inputImage1Component_2")
        self.horizontalLayout_2.addWidget(self.inputImage1Component_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Upload2 = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Upload2.sizePolicy().hasHeightForWidth())
        self.Upload2.setSizePolicy(sizePolicy)
        self.Upload2.setMinimumSize(QtCore.QSize(0, 30))
        self.Upload2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.Upload2.setObjectName("Upload2")
        self.horizontalLayout_4.addWidget(self.Upload2)
        self.inputComponents2 = QtWidgets.QToolButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputComponents2.sizePolicy().hasHeightForWidth())
        self.inputComponents2.setSizePolicy(sizePolicy)
        self.inputComponents2.setMinimumSize(QtCore.QSize(0, 30))
        self.inputComponents2.setStyleSheet("selection-background-color: rgb(0, 73, 220);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.inputComponents2.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.inputComponents2.setObjectName("inputComponents2")
        self.horizontalLayout_4.addWidget(self.inputComponents2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.inputImage2 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputImage2.sizePolicy().hasHeightForWidth())
        self.inputImage2.setSizePolicy(sizePolicy)
        self.inputImage2.setMinimumSize(QtCore.QSize(300, 200))
        self.inputImage2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputImage2.setFrameShape(QtWidgets.QFrame.Box)
        self.inputImage2.setText("")
        self.inputImage2.setObjectName("inputImage2")
        self.horizontalLayout_5.addWidget(self.inputImage2)
        self.inputImage2Component = PlotWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputImage2Component.sizePolicy().hasHeightForWidth())
        self.inputImage2Component.setSizePolicy(sizePolicy)
        self.inputImage2Component.setMinimumSize(QtCore.QSize(300, 200))
        self.inputImage2Component.setObjectName("inputImage2Component")
        self.horizontalLayout_5.addWidget(self.inputImage2Component)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output1 = PlotWidget(self.tab2)
        self.output1.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.output1.setFrameShape(QtWidgets.QFrame.Box)
        self.output1.setObjectName("output1")
        self.horizontalLayout.addWidget(self.output1)
        self.output2 = PlotWidget(self.tab2)
        self.output2.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.output2.setFrameShape(QtWidgets.QFrame.Box)
        self.output2.setObjectName("output2")
        self.horizontalLayout.addWidget(self.output2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 0, 1, 3)
        self.s2Value = QtWidgets.QLabel(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2Value.sizePolicy().hasHeightForWidth())
        self.s2Value.setSizePolicy(sizePolicy)
        self.s2Value.setMinimumSize(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.s2Value.setFont(font)
        self.s2Value.setStyleSheet("\n"
"")
        self.s2Value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.s2Value.setText("")
        self.s2Value.setAlignment(QtCore.Qt.AlignCenter)
        self.s2Value.setObjectName("s2Value")
        self.gridLayout_2.addWidget(self.s2Value, 5, 2, 1, 1)
        self.s1Value = QtWidgets.QLabel(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1Value.sizePolicy().hasHeightForWidth())
        self.s1Value.setSizePolicy(sizePolicy)
        self.s1Value.setMinimumSize(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.s1Value.setFont(font)
        self.s1Value.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.s1Value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.s1Value.setText("")
        self.s1Value.setAlignment(QtCore.Qt.AlignCenter)
        self.s1Value.setObjectName("s1Value")
        self.gridLayout_2.addWidget(self.s1Value, 2, 2, 1, 1)
        self.component2Label = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.component2Label.setFont(font)
        self.component2Label.setObjectName("component2Label")
        self.gridLayout_2.addWidget(self.component2Label, 3, 0, 1, 1)
        self.component1Label = QtWidgets.QLabel(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.component1Label.sizePolicy().hasHeightForWidth())
        self.component1Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.component1Label.setFont(font)
        self.component1Label.setObjectName("component1Label")
        self.gridLayout_2.addWidget(self.component1Label, 1, 0, 1, 1)
        self.mixerLabel = QtWidgets.QLabel(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mixerLabel.sizePolicy().hasHeightForWidth())
        self.mixerLabel.setSizePolicy(sizePolicy)
        self.mixerLabel.setMinimumSize(QtCore.QSize(300, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.mixerLabel.setFont(font)
        self.mixerLabel.setToolTipDuration(3)
        self.mixerLabel.setIndent(-2)
        self.mixerLabel.setObjectName("mixerLabel")
        self.gridLayout_2.addWidget(self.mixerLabel, 0, 0, 1, 1)
        self.imgChoice1 = QtWidgets.QToolButton(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgChoice1.sizePolicy().hasHeightForWidth())
        self.imgChoice1.setSizePolicy(sizePolicy)
        self.imgChoice1.setMinimumSize(QtCore.QSize(300, 28))
        self.imgChoice1.setStyleSheet("selection-background-color: rgb(0, 73, 220);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.imgChoice1.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.imgChoice1.setObjectName("imgChoice1")
        self.gridLayout_2.addWidget(self.imgChoice1, 2, 0, 1, 1)
        self.imgChoice2 = QtWidgets.QToolButton(self.tab2)
        self.imgChoice2.setMinimumSize(QtCore.QSize(300, 28))
        self.imgChoice2.setStyleSheet("selection-background-color: rgb(0, 73, 220);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.imgChoice2.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.imgChoice2.setObjectName("imgChoice2")
        self.gridLayout_2.addWidget(self.imgChoice2, 4, 0, 2, 1)
        self.outputChoice = QtWidgets.QToolButton(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputChoice.sizePolicy().hasHeightForWidth())
        self.outputChoice.setSizePolicy(sizePolicy)
        self.outputChoice.setMinimumSize(QtCore.QSize(300, 0))
        self.outputChoice.setStyleSheet("selection-background-color: rgb(0, 73, 220);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.outputChoice.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.outputChoice.setObjectName("outputChoice")
        self.gridLayout_2.addWidget(self.outputChoice, 0, 1, 1, 2)
        self.slider1 = QtWidgets.QSlider(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider1.sizePolicy().hasHeightForWidth())
        self.slider1.setSizePolicy(sizePolicy)
        self.slider1.setMinimumSize(QtCore.QSize(280, 0))
        self.slider1.setMaximumSize(QtCore.QSize(194, 16777215))
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.gridLayout_2.addWidget(self.slider1, 2, 1, 1, 1)
        self.componentsChoice1 = QtWidgets.QToolButton(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.componentsChoice1.sizePolicy().hasHeightForWidth())
        self.componentsChoice1.setSizePolicy(sizePolicy)
        self.componentsChoice1.setMinimumSize(QtCore.QSize(300, 22))
        self.componentsChoice1.setStyleSheet("selection-background-color: rgb(0, 73, 220);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.componentsChoice1.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.componentsChoice1.setObjectName("componentsChoice1")
        self.gridLayout_2.addWidget(self.componentsChoice1, 1, 1, 1, 2)
        self.componentsChoice2 = QtWidgets.QToolButton(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.componentsChoice2.sizePolicy().hasHeightForWidth())
        self.componentsChoice2.setSizePolicy(sizePolicy)
        self.componentsChoice2.setMinimumSize(QtCore.QSize(300, 22))
        self.componentsChoice2.setStyleSheet("selection-background-color: rgb(0, 73, 220);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 207, 207);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"padding: 4px;")
        self.componentsChoice2.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.componentsChoice2.setObjectName("componentsChoice2")
        self.gridLayout_2.addWidget(self.componentsChoice2, 3, 1, 2, 2)
        self.slider2 = QtWidgets.QSlider(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider2.sizePolicy().hasHeightForWidth())
        self.slider2.setSizePolicy(sizePolicy)
        self.slider2.setMinimumSize(QtCore.QSize(280, 0))
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.gridLayout_2.addWidget(self.slider2, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMagnitude = QtWidgets.QAction(MainWindow)
        self.actionMagnitude.setObjectName("actionMagnitude")
        self.actionPhase = QtWidgets.QAction(MainWindow)
        self.actionPhase.setObjectName("actionPhase")
        self.actionMagnitude_2 = QtWidgets.QAction(MainWindow)
        self.actionMagnitude_2.setObjectName("actionMagnitude_2")
        self.actionPhase_2 = QtWidgets.QAction(MainWindow)
        self.actionPhase_2.setObjectName("actionPhase_2")
        self.actionReal = QtWidgets.QAction(MainWindow)
        self.actionReal.setObjectName("actionReal")
        self.actionImaginary = QtWidgets.QAction(MainWindow)
        self.actionImaginary.setObjectName("actionImaginary")
        self.actionReal_2 = QtWidgets.QAction(MainWindow)
        self.actionReal_2.setObjectName("actionReal_2")
        self.actionImaginary_2 = QtWidgets.QAction(MainWindow)
        self.actionImaginary_2.setObjectName("actionImaginary_2")
        self.actionImage1 = QtWidgets.QAction(MainWindow)
        self.actionImage1.setObjectName("actionImage1")
        self.actionImage2 = QtWidgets.QAction(MainWindow)
        self.actionImage2.setObjectName("actionImage2")
        self.actionImage11 = QtWidgets.QAction(MainWindow)
        self.actionImage11.setObjectName("actionImage11")
        self.actionImage22 = QtWidgets.QAction(MainWindow)
        self.actionImage22.setObjectName("actionImage22")
        self.actionOutput_1 = QtWidgets.QAction(MainWindow)
        self.actionOutput_1.setObjectName("actionOutput_1")
        self.actionOutput_2 = QtWidgets.QAction(MainWindow)
        self.actionOutput_2.setObjectName("actionOutput_2")
        self.actionMagnitude_3 = QtWidgets.QAction(MainWindow)
        self.actionMagnitude_3.setObjectName("actionMagnitude_3")
        self.actionPhase_3 = QtWidgets.QAction(MainWindow)
        self.actionPhase_3.setObjectName("actionPhase_3")
        self.actionReal_3 = QtWidgets.QAction(MainWindow)
        self.actionReal_3.setObjectName("actionReal_3")
        self.actionImaginary_3 = QtWidgets.QAction(MainWindow)
        self.actionImaginary_3.setObjectName("actionImaginary_3")
        self.actionUniform_Magnitude = QtWidgets.QAction(MainWindow)
        self.actionUniform_Magnitude.setObjectName("actionUniform_Magnitude")
        self.actionUniform_Phase = QtWidgets.QAction(MainWindow)
        self.actionUniform_Phase.setObjectName("actionUniform_Phase")
        self.actionMagnitude_4 = QtWidgets.QAction(MainWindow)
        self.actionMagnitude_4.setObjectName("actionMagnitude_4")
        self.actionPhase_4 = QtWidgets.QAction(MainWindow)
        self.actionPhase_4.setObjectName("actionPhase_4")
        self.actionReal_4 = QtWidgets.QAction(MainWindow)
        self.actionReal_4.setObjectName("actionReal_4")
        self.actionImaginary_4 = QtWidgets.QAction(MainWindow)
        self.actionImaginary_4.setObjectName("actionImaginary_4")
        self.actionUniform_Magnitude_2 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Magnitude_2.setObjectName("actionUniform_Magnitude_2")
        self.actionUniform_Phase_2 = QtWidgets.QAction(MainWindow)
        self.actionUniform_Phase_2.setObjectName("actionUniform_Phase_2")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Upload_2.setText(_translate("MainWindow", "Upload 1st Image"))
        self.inputComponents1_2.setText(_translate("MainWindow", "Components"))
        self.Upload2.setText(_translate("MainWindow", "Upload 2nd Image"))
        self.inputComponents2.setText(_translate("MainWindow", "Components"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Sliders"))
        self.component2Label.setText(_translate("MainWindow", "Component 2:"))
        self.component1Label.setText(_translate("MainWindow", "Component 1:"))
        self.mixerLabel.setText(_translate("MainWindow", "Mixer Output To:"))
        self.imgChoice1.setText(_translate("MainWindow", "Img 1, Img 2"))
        self.imgChoice2.setText(_translate("MainWindow", "Img 1, Img 2"))
        self.outputChoice.setText(_translate("MainWindow", "Output 1, Output 2"))
        self.componentsChoice1.setText(_translate("MainWindow", "Components"))
        self.componentsChoice2.setText(_translate("MainWindow", "Components"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Mixer"))
        self.actionMagnitude.setText(_translate("MainWindow", "Magnitude"))
        self.actionPhase.setText(_translate("MainWindow", "Phase"))
        self.actionMagnitude_2.setText(_translate("MainWindow", "Magnitude"))
        self.actionPhase_2.setText(_translate("MainWindow", "Phase"))
        self.actionReal.setText(_translate("MainWindow", "Real"))
        self.actionImaginary.setText(_translate("MainWindow", "Imaginary"))
        self.actionReal_2.setText(_translate("MainWindow", "Real"))
        self.actionImaginary_2.setText(_translate("MainWindow", "Imaginary"))
        self.actionImage1.setText(_translate("MainWindow", "Image 1"))
        self.actionImage2.setText(_translate("MainWindow", "Image 2"))
        self.actionImage11.setText(_translate("MainWindow", "Image 1"))
        self.actionImage22.setText(_translate("MainWindow", "Image 2"))
        self.actionOutput_1.setText(_translate("MainWindow", "Output 1"))
        self.actionOutput_2.setText(_translate("MainWindow", "Output 2"))
        self.actionMagnitude_3.setText(_translate("MainWindow", "Magnitude "))
        self.actionPhase_3.setText(_translate("MainWindow", "Phase"))
        self.actionReal_3.setText(_translate("MainWindow", "Real"))
        self.actionImaginary_3.setText(_translate("MainWindow", "Imaginary"))
        self.actionUniform_Magnitude.setText(_translate("MainWindow", "Uniform Magnitude"))
        self.actionUniform_Phase.setText(_translate("MainWindow", "Uniform Phase"))
        self.actionMagnitude_4.setText(_translate("MainWindow", "Magnitude"))
        self.actionPhase_4.setText(_translate("MainWindow", "Phase"))
        self.actionReal_4.setText(_translate("MainWindow", "Real"))
        self.actionImaginary_4.setText(_translate("MainWindow", "Imaginary"))
        self.actionUniform_Magnitude_2.setText(_translate("MainWindow", "Uniform Magnitude"))
        self.actionUniform_Phase_2.setText(_translate("MainWindow", "Uniform Phase"))

from pyqtgraph import PlotWidget
